version: "3.9"
services:
    api:
        build:
            context: ./FeedsApi
            dockerfile: ./Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://+:5008     
        ports:
            - 5008:5008
    worker:
        build:
            context: ./FeedsWorker
            dockerfile: ./Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Development  
            
